version: "3.1"

services:
  infisical-agent:
    container_name: infisical-agnet
    image: infisical/cli:0.17.4
    command: agent --config=/run/secrets/infisical_agent_config
    volumes:
      - infisical-secrets:/infisical-secrets
    secrets:
      - infisical_universal_auth_client_id
      - infisical_universal_client_secret
      - infisical_agent_config
      - dot_env_secret_template

secrets:
  infisical_universal_auth_client_id:
    file: ./client-id
  infisical_universal_client_secret:
    file: ./client-secret
  infisical_agent_config:
    file: ./infisical-agent-config
  dot_env_secret_template:
    file: ./dot-env-secret-template

volumes:
  infisical-secrets: 
    

  